# Site
# repository: enesdemirag/enesdemirag.github.io
favicon: images/favicon.ico

# Personal info
name: Enes Demirağ
title: Software Developer
email: demirag16@itu.edu.tr
# website: www.enesdemirag.github.io

# Social links
# twitter_username: facespics
github_username: enesdemirag
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Enes and I'm a student at Istanbul Technical University. I am studying Electronics and Communication Engineering. As well as programming I also have experience in electronics. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in <mark>Python</mark> programming. You can check my <mark>[LinkedIn](https://www.linkedin.com/in/enesdemirag/)</mark> profile.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Computer Skills
more_content: | # this will include new lines to allow paragraphs
  - Office
  - Python
  - C
  - C#

  ### Technical Skills
  - Linux
  - Robotics
  - Image Processing
  - Microcontrollers
  - Arduino
  - Raspberry Pi
  - ROVs
  - Autonomous Vehicles

  ### Awards
  - <mark>2018</mark> Teknofest Underwater Systems Competition 4th - *Istanbul / Turkey*
  - <mark>2018</mark> MATE ROV International Competition 11th - *Federal Way, Washington / USA*
  - <mark>2018</mark> MATE ROV Regional Competition 1st - *Istanbul / Turkey*
  - <mark>2017</mark> MATE ROV International Competition 23rd - *Long Beach, California / USA*
  - <mark>2017</mark> MATE ROV Regional Competition 1st - *Istanbul / Turkey*

  ### Hobbies
   - Comics
   - Computer Games
   - Role Playing Games
   - Cinema

# TODO: Languages, Certificates, and others

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
