# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Enes Demirağ
title: Software Developer
email: enesdemirag@ituauv.com
website: www.enesdemirag.github.io

# Social links
# twitter_username: facespics
github_username: enesdemirag
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Enes and I'm a student at Istanbul Technical University. I am studying Electronics and Communication Engineering. As well as programming I also have experience in electronics. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>C</mark> and <mark>Python</mark> programming.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in robotics some of my other interests and hobbies are:
   - Comics
   - Computer Games
   - Role Playing Games
   - Cinema

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
