# Site
# repository: enesdemirag/enesdemirag.github.io
favicon: images/favicon.ico

# Personal info
name: Enes Demirağ
title: Software Developer
email: demirag16@itu.edu.tr
# website: www.enesdemirag.github.io

# Social links
# twitter_username: facespics
github_username: enesdemirag
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Enes and I'm a student at Istanbul Technical University. I am studying Electronics and Communication Engineering. As well as programming I also have experience in electronics. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in <mark>Robotics</mark> and currently working on an underwater robotics project. You can check my **[LinkedIn](https://www.linkedin.com/in/enesdemirag/)** profile.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Computer Skills
more_content: | # this will include new lines to allow paragraphs
  - Office Programs
  - Python
  - C
  - C#
  - Linux
  - Git
  - OpenCV
  - Tensorflow
  - ROS

  ### Technical Skills
  - Arduino
  - Raspberry Pi
  - ROVs & AUVs
  - Stereo Cameras

  ### Awards
  <mark>2018</mark>
    - Teknofest Underwater Systems Competition 4th - *Istanbul / Turkey*
    - MATE ROV International Competition 11th - *Federal Way, Washington / USA*
    - MATE ROV Regional Competition 1st - *Istanbul / Turkey*

  <mark>2017</mark>
    - MATE ROV International Competition 23rd - *Long Beach, California / USA*
    - MATE ROV Regional Competition 1st - *Istanbul / Turkey*

  ### Hobbies
   - Comics
   - Computer Games
   - Role Playing Games
   - Cinema

  ### Communities
  <mark>ITU Robotics Club</mark> : Previously known as ARIGE is a robotics club among Istanbul Technical University. The club has many achievements, tons of opportunity for Research and Development projects with great minds. Can handle any size of project from micro robots to mars rovers and underwater vehicles. A cool place for the robot enthusiasts in the ITU campus.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
